/**
 * Unified API Router for Cloudflare Pages Functions
 * Migrated from backend/api/index.js Worker format
 * Handles ALL /api/* requests with full backend functionality
 */

// Import Neural Cross-Pollination Handlers
import {
    handleGoldenThreadExtract,
    handleGetActiveBuffer,
    handleGoldenThreadVerify,
    handleGoldenThreadFlashback,
    handleRecordMetrics,
    handleGetIntervention,
    handleSuccessFeedback,
    handleWeeklyUserReport,
    handlePopulationInsights
} from '../../../backend/api/neural_handlers.js';

// Import Collective Intelligence Handlers
import {
    handleHiveAggregate,
    handleGetRegionalWeakness,
    handleNationalHeatmap,
    handleNationalVelocity
} from '../../../backend/api/regional_analytics.js';

import {
    handleRegionalQuestGeneration,
    handleDailyNationalChallenge,
    handleGetActiveRegionalEvents,
    handleGetDailyChallenge
} from '../../../backend/api/auto_event_generator.js';

import {
    handleNewsScrapingJob,
    handleNewsToDungeon,
    handleGetCurrentEvents,
    handleAutoGenerateDungeons
} from '../../../backend/api/infinite_lore_generator.js';

import {
    handleRegisterPartner,
    handleGovernmentLiteracyHeatmap,
    handleUniversityEliteProfiles,
    handleClaimProfile,
    handleWeaknessStream
} from '../../../backend/api/sultan_api.js';

// Import Writing Handlers
import {
    handleAutoSave,
    handleRealtimeAnalysis,
    handleSubmit
} from '../../../backend/api/writing_kv_handler.js';

import {
    handleSubmitAsync,
    handleGetSubmissionStatus
} from '../../../backend/api/writing_queue_handler.js';

// Import Speaking Handlers
import {
    handleSpeakingInit,
    handleChunkUpload,
    handleSpeakingFinalize,
    handleSpeakingStatus
} from '../../../backend/api/speaking_r2_handler.js';

import { handleGetUploadUrl } from '../../../backend/api/speaking/get_upload_url.js';

// Import Core Handlers
import { handleHealthCheck } from '../../../backend/api/health_check.js';
import { handleOnboarding } from '../../../backend/api/onboarding_handler.js';
import { handleNextMission } from '../../../backend/api/mission_routing.js';
import { handleSocial } from '../../../backend/api/social_handler.js';
import { handleMiniGameValidate } from '../../../backend/api/minigames/sentence_architect.js';

export async function onRequest(context) {
    const { request, env, params } = context;
    const url = new URL(request.url);
    const pathname = url.pathname;
    const method = request.method;

    // CORS headers
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    };

    // Handle OPTIONS preflight
    if (method === 'OPTIONS') {
        return new Response(null, { headers: corsHeaders });
    }

    try {
        // ============= HEALTH & STATUS =============
        if (pathname === '/api/health-check') {
            return await handleHealthCheck(request, env, corsHeaders);
        }

        // ============= WRITING ENDPOINTS =============
        if (pathname === '/api/writing/save' && method === 'PUT') {
            return await handleAutoSave(request, env, corsHeaders);
        }
        if (pathname === '/api/writing/analyze' && method === 'POST') {
            return await handleRealtimeAnalysis(request, env, corsHeaders);
        }
        if (pathname === '/api/writing/submit' && method === 'POST') {
            return await handleSubmit(request, env, corsHeaders);
        }
        if (pathname === '/api/writing/submit-async' && method === 'POST') {
            return await handleSubmitAsync(request, env, corsHeaders);
        }
        if (pathname.startsWith('/api/submissions/') && method === 'GET') {
            return await handleGetSubmissionStatus(request, env, corsHeaders);
        }

        // ============= SPEAKING ENDPOINTS =============
        if (pathname === '/api/speaking/init' && method === 'POST') {
            return await handleSpeakingInit(request, env, corsHeaders);
        }
        if (pathname === '/api/speaking/upload-chunk' && method === 'POST') {
            return await handleChunkUpload(request, env, corsHeaders);
        }
        if (pathname === '/api/speaking/finalize' && method === 'POST') {
            return await handleSpeakingFinalize(request, env, corsHeaders);
        }
        if (pathname.startsWith('/api/speaking/status/') && method === 'GET') {
            return await handleSpeakingStatus(request, env, corsHeaders);
        }
        if (pathname === '/api/speaking/get-upload-url' && method === 'POST') {
            return await handleGetUploadUrl(request, env, corsHeaders);
        }

        // ============= NEURAL CROSS-POLLINATION =============
        if (pathname === '/api/neural/extract' && method === 'POST') {
            return await handleGoldenThreadExtract(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/buffer' && method === 'GET') {
            return await handleGetActiveBuffer(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/verify' && method === 'POST') {
            return await handleGoldenThreadVerify(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/flashback' && method === 'GET') {
            return await handleGoldenThreadFlashback(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/metrics' && method === 'POST') {
            return await handleRecordMetrics(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/intervention' && method === 'GET') {
            return await handleGetIntervention(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/success' && method === 'POST') {
            return await handleSuccessFeedback(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/weekly-report' && method === 'GET') {
            return await handleWeeklyUserReport(request, env, corsHeaders);
        }
        if (pathname === '/api/neural/population' && method === 'GET') {
            return await handlePopulationInsights(request, env, corsHeaders);
        }

        // ============= REGIONAL ANALYTICS =============
        if (pathname === '/api/regional/aggregate' && method === 'POST') {
            return await handleHiveAggregate(request, env, corsHeaders);
        }
        if (pathname === '/api/regional/weakness' && method === 'GET') {
            return await handleGetRegionalWeakness(request, env, corsHeaders);
        }
        if (pathname === '/api/regional/heatmap' && method === 'GET') {
            return await handleNationalHeatmap(request, env, corsHeaders);
        }
        if (pathname === '/api/regional/velocity' && method === 'GET') {
            return await handleNationalVelocity(request, env, corsHeaders);
        }

        // ============= AUTO-EVENTS & QUESTS =============
        if (pathname === '/api/auto-forge/regional-quest' && method === 'POST') {
            return await handleRegionalQuestGeneration(request, env, corsHeaders);
        }
        if (pathname === '/api/auto-forge/daily-challenge' && method === 'GET') {
            return await handleGetDailyChallenge(request, env, corsHeaders);
        }
        if (pathname === '/api/auto-forge/national-challenge' && method === 'POST') {
            return await handleDailyNationalChallenge(request, env, corsHeaders);
        }
        if (pathname === '/api/auto-forge/active-events' && method === 'GET') {
            return await handleGetActiveRegionalEvents(request, env, corsHeaders);
        }

        // ============= INFINITE LORE GENERATOR =============
        if (pathname === '/api/lore/scrape-news' && method === 'POST') {
            return await handleNewsScrapingJob(request, env, corsHeaders);
        }
        if (pathname === '/api/lore/news-to-dungeon' && method === 'POST') {
            return await handleNewsToDungeon(request, env, corsHeaders);
        }
        if (pathname === '/api/lore/current-events' && method === 'GET') {
            return await handleGetCurrentEvents(request, env, corsHeaders);
        }
        if (pathname === '/api/lore/auto-generate' && method === 'POST') {
            return await handleAutoGenerateDungeons(request, env, corsHeaders);
        }

        // ============= SULTAN / B2B API =============
        if (pathname === '/api/sultan/register-partner' && method === 'POST') {
            return await handleRegisterPartner(request, env, corsHeaders);
        }
        if (pathname === '/api/sultan/literacy-heatmap' && method === 'GET') {
            return await handleGovernmentLiteracyHeatmap(request, env, corsHeaders);
        }
        if (pathname === '/api/sultan/university-profiles' && method === 'GET') {
            return await handleUniversityEliteProfiles(request, env, corsHeaders);
        }
        if (pathname === '/api/sultan/claim-profile' && method === 'POST') {
            return await handleClaimProfile(request, env, corsHeaders);
        }
        if (pathname === '/api/sultan/weakness-stream' && method === 'GET') {
            return await handleWeaknessStream(request, env, corsHeaders);
        }

        // ============= USER & ONBOARDING =============
        if (pathname === '/api/onboarding' && method === 'POST') {
            return await handleOnboarding(request, env, corsHeaders);
        }
        if (pathname === '/api/next-mission' && method === 'GET') {
            return await handleNextMission(request, env, corsHeaders);
        }

        // ============= SOCIAL / GUILDS =============
        if (pathname.startsWith('/api/social/')) {
            return await handleSocial(request, env, corsHeaders);
        }

        // ============= MINI-GAMES =============
        if (pathname === '/api/minigames/sentence-architect/validate' && method === 'POST') {
            return await handleMiniGameValidate(request, env, corsHeaders);
        }

        // ============= 404 NOT FOUND =============
        return new Response(JSON.stringify({
            error: 'API endpoint not found',
            path: pathname,
            method: method,
            hint: 'Check API documentation for available endpoints'
        }), {
            status: 404,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });

    } catch (error) {
        console.error('API Error:', error);
        return new Response(JSON.stringify({
            error: 'Internal server error',
            message: error.message,
            stack: error.stack?.split('\n').slice(0, 3)
        }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
    }
}
